{
  "name": "All",
  "on": [
    "push",
    "pull_request"
  ],
  "jobs": {
    "test": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Setup | Checkout",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Setup | Install Dotnet",
          "uses": "actions/setup-dotnet@v1",
          "with": {
            "dotnet-version": "6.0.x"
          }
        },
        {
          "name": "Check | Tests",
          "run": "dotnet test"
        }
      ]
    },
    "release": {
      "name": "Build and Release",
      "needs": "test",
      "if": "github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')",
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Setup | Checkout",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Setup | Install Dotnet",
          "uses": "actions/setup-dotnet@v1",
          "with": {
            "dotnet-version": "6.0.x"
          }
        },
        {
          "name": "Build | Build",
          "run": "pwsh ./build.ps1 -release\n7z a Dotenv.zip Dotenv"
        },
        {
          "name": "Setup | go",
          "uses": "actions/setup-go@v2",
          "with": {
            "go-version": "^1.15.7"
          }
        },
        {
          "name": "Setup | Release notes",
          "run": "GO111MODULE=on go install github.com/git-chglog/git-chglog/cmd/git-chglog@v0.15.1\ngit-chglog -c .github/chglog/release.yml \"$(git describe --tags)\" > RELEASE.md"
        },
        {
          "name": "Deploy | Publish",
          "uses": "softprops/action-gh-release@v1",
          "with": {
            "files": "Dotenv.zip",
            "body_path": "RELEASE.md"
          }
        }
      ]
    }
  }
}
